package com.sealll.mapper;

import com.sealll.application.message.bean.Message2;
import com.sealll.application.message.bean.Message2Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Message2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    long countByExample(Message2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    int deleteByExample(Message2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    int insert(Message2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    int insertSelective(Message2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    List<Message2> selectByExample(Message2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") Message2 record, @Param("example") Message2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    int updateByExample(@Param("record") Message2 record, @Param("example") Message2Example example);
}