package com.sealll.mapper;

import com.sealll.bean.Perm;
import com.sealll.bean.PermExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    long countByExample(PermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    int deleteByExample(PermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    int deleteByPrimaryKey(String perId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    int insert(Perm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    int insertSelective(Perm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    List<Perm> selectByExample(PermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    Perm selectByPrimaryKey(String perId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    int updateByExampleSelective(@Param("record") Perm record, @Param("example") PermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    int updateByExample(@Param("record") Perm record, @Param("example") PermExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    int updateByPrimaryKeySelective(Perm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    int updateByPrimaryKey(Perm record);
}