package com.sealll.bean;

import java.util.Date;

public class Post {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.p_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.uid
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.title
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column post.content
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.p_id
     *
     * @return the value of post.p_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.p_id
     *
     * @param pId the value for post.p_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.uid
     *
     * @return the value of post.uid
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.uid
     *
     * @param uid the value for post.uid
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.title
     *
     * @return the value of post.title
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.title
     *
     * @param title the value for post.title
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.time
     *
     * @return the value of post.time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.time
     *
     * @param time the value for post.time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column post.content
     *
     * @return the value of post.content
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column post.content
     *
     * @param content the value for post.content
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}