package com.sealll.bean;

import java.util.Date;

public class Reply extends ReplyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.uid
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.stars
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String stars;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.content
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private byte[] content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.uid
     *
     * @return the value of reply.uid
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.uid
     *
     * @param uid the value for reply.uid
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.stars
     *
     * @return the value of reply.stars
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getStars() {
        return stars;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.stars
     *
     * @param stars the value for reply.stars
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setStars(String stars) {
        this.stars = stars == null ? null : stars.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.time
     *
     * @return the value of reply.time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.time
     *
     * @param time the value for reply.time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.content
     *
     * @return the value of reply.content
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public byte[] getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.content
     *
     * @param content the value for reply.content
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setContent(byte[] content) {
        this.content = content;
    }
}