package com.sealll.bean;

import java.util.Date;

public class Subscribe {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribe.sub_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String subId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribe.subing
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String subing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribe.subbed
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String subbed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscribe.sub_time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private Date subTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribe.sub_id
     *
     * @return the value of subscribe.sub_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribe.sub_id
     *
     * @param subId the value for subscribe.sub_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setSubId(String subId) {
        this.subId = subId == null ? null : subId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribe.subing
     *
     * @return the value of subscribe.subing
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getSubing() {
        return subing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribe.subing
     *
     * @param subing the value for subscribe.subing
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setSubing(String subing) {
        this.subing = subing == null ? null : subing.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribe.subbed
     *
     * @return the value of subscribe.subbed
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getSubbed() {
        return subbed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribe.subbed
     *
     * @param subbed the value for subscribe.subbed
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setSubbed(String subbed) {
        this.subbed = subbed == null ? null : subbed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscribe.sub_time
     *
     * @return the value of subscribe.sub_time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public Date getSubTime() {
        return subTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscribe.sub_time
     *
     * @param subTime the value for subscribe.sub_time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setSubTime(Date subTime) {
        this.subTime = subTime;
    }
}