package com.sealll.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SubscribeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public SubscribeExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubIdIsNull() {
            addCriterion("sub_id is null");
            return (Criteria) this;
        }

        public Criteria andSubIdIsNotNull() {
            addCriterion("sub_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubIdEqualTo(String value) {
            addCriterion("sub_id =", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdNotEqualTo(String value) {
            addCriterion("sub_id <>", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdGreaterThan(String value) {
            addCriterion("sub_id >", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdGreaterThanOrEqualTo(String value) {
            addCriterion("sub_id >=", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdLessThan(String value) {
            addCriterion("sub_id <", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdLessThanOrEqualTo(String value) {
            addCriterion("sub_id <=", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdLike(String value) {
            addCriterion("sub_id like", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdNotLike(String value) {
            addCriterion("sub_id not like", value, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdIn(List<String> values) {
            addCriterion("sub_id in", values, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdNotIn(List<String> values) {
            addCriterion("sub_id not in", values, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdBetween(String value1, String value2) {
            addCriterion("sub_id between", value1, value2, "subId");
            return (Criteria) this;
        }

        public Criteria andSubIdNotBetween(String value1, String value2) {
            addCriterion("sub_id not between", value1, value2, "subId");
            return (Criteria) this;
        }

        public Criteria andSubingIsNull() {
            addCriterion("subing is null");
            return (Criteria) this;
        }

        public Criteria andSubingIsNotNull() {
            addCriterion("subing is not null");
            return (Criteria) this;
        }

        public Criteria andSubingEqualTo(String value) {
            addCriterion("subing =", value, "subing");
            return (Criteria) this;
        }

        public Criteria andSubingNotEqualTo(String value) {
            addCriterion("subing <>", value, "subing");
            return (Criteria) this;
        }

        public Criteria andSubingGreaterThan(String value) {
            addCriterion("subing >", value, "subing");
            return (Criteria) this;
        }

        public Criteria andSubingGreaterThanOrEqualTo(String value) {
            addCriterion("subing >=", value, "subing");
            return (Criteria) this;
        }

        public Criteria andSubingLessThan(String value) {
            addCriterion("subing <", value, "subing");
            return (Criteria) this;
        }

        public Criteria andSubingLessThanOrEqualTo(String value) {
            addCriterion("subing <=", value, "subing");
            return (Criteria) this;
        }

        public Criteria andSubingLike(String value) {
            addCriterion("subing like", value, "subing");
            return (Criteria) this;
        }

        public Criteria andSubingNotLike(String value) {
            addCriterion("subing not like", value, "subing");
            return (Criteria) this;
        }

        public Criteria andSubingIn(List<String> values) {
            addCriterion("subing in", values, "subing");
            return (Criteria) this;
        }

        public Criteria andSubingNotIn(List<String> values) {
            addCriterion("subing not in", values, "subing");
            return (Criteria) this;
        }

        public Criteria andSubingBetween(String value1, String value2) {
            addCriterion("subing between", value1, value2, "subing");
            return (Criteria) this;
        }

        public Criteria andSubingNotBetween(String value1, String value2) {
            addCriterion("subing not between", value1, value2, "subing");
            return (Criteria) this;
        }

        public Criteria andSubbedIsNull() {
            addCriterion("subbed is null");
            return (Criteria) this;
        }

        public Criteria andSubbedIsNotNull() {
            addCriterion("subbed is not null");
            return (Criteria) this;
        }

        public Criteria andSubbedEqualTo(String value) {
            addCriterion("subbed =", value, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubbedNotEqualTo(String value) {
            addCriterion("subbed <>", value, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubbedGreaterThan(String value) {
            addCriterion("subbed >", value, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubbedGreaterThanOrEqualTo(String value) {
            addCriterion("subbed >=", value, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubbedLessThan(String value) {
            addCriterion("subbed <", value, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubbedLessThanOrEqualTo(String value) {
            addCriterion("subbed <=", value, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubbedLike(String value) {
            addCriterion("subbed like", value, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubbedNotLike(String value) {
            addCriterion("subbed not like", value, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubbedIn(List<String> values) {
            addCriterion("subbed in", values, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubbedNotIn(List<String> values) {
            addCriterion("subbed not in", values, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubbedBetween(String value1, String value2) {
            addCriterion("subbed between", value1, value2, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubbedNotBetween(String value1, String value2) {
            addCriterion("subbed not between", value1, value2, "subbed");
            return (Criteria) this;
        }

        public Criteria andSubTimeIsNull() {
            addCriterion("sub_time is null");
            return (Criteria) this;
        }

        public Criteria andSubTimeIsNotNull() {
            addCriterion("sub_time is not null");
            return (Criteria) this;
        }

        public Criteria andSubTimeEqualTo(Date value) {
            addCriterion("sub_time =", value, "subTime");
            return (Criteria) this;
        }

        public Criteria andSubTimeNotEqualTo(Date value) {
            addCriterion("sub_time <>", value, "subTime");
            return (Criteria) this;
        }

        public Criteria andSubTimeGreaterThan(Date value) {
            addCriterion("sub_time >", value, "subTime");
            return (Criteria) this;
        }

        public Criteria andSubTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sub_time >=", value, "subTime");
            return (Criteria) this;
        }

        public Criteria andSubTimeLessThan(Date value) {
            addCriterion("sub_time <", value, "subTime");
            return (Criteria) this;
        }

        public Criteria andSubTimeLessThanOrEqualTo(Date value) {
            addCriterion("sub_time <=", value, "subTime");
            return (Criteria) this;
        }

        public Criteria andSubTimeIn(List<Date> values) {
            addCriterion("sub_time in", values, "subTime");
            return (Criteria) this;
        }

        public Criteria andSubTimeNotIn(List<Date> values) {
            addCriterion("sub_time not in", values, "subTime");
            return (Criteria) this;
        }

        public Criteria andSubTimeBetween(Date value1, Date value2) {
            addCriterion("sub_time between", value1, value2, "subTime");
            return (Criteria) this;
        }

        public Criteria andSubTimeNotBetween(Date value1, Date value2) {
            addCriterion("sub_time not between", value1, value2, "subTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subscribe
     *
     * @mbg.generated do_not_delete_during_merge Sun Mar 28 15:51:14 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}