package com.sealll.bean;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.uid
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.username
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.password
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.description
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.reg_time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private Date regTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.uid
     *
     * @return the value of User.uid
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.uid
     *
     * @param uid the value for User.uid
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.username
     *
     * @return the value of User.username
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.username
     *
     * @param username the value for User.username
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.password
     *
     * @return the value of User.password
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.password
     *
     * @param password the value for User.password
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.description
     *
     * @return the value of User.description
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.description
     *
     * @param description the value for User.description
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.reg_time
     *
     * @return the value of User.reg_time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.reg_time
     *
     * @param regTime the value for User.reg_time
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }
}