package com.sealll.mapper;

import com.sealll.bean.Subscribe;
import com.sealll.bean.SubscribeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubscribeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    long countByExample(SubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    int deleteByExample(SubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    int deleteByPrimaryKey(String subId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    int insert(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    int insertSelective(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    List<Subscribe> selectByExample(SubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    Subscribe selectByPrimaryKey(String subId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") Subscribe record, @Param("example") SubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    int updateByExample(@Param("record") Subscribe record, @Param("example") SubscribeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    int updateByPrimaryKeySelective(Subscribe record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscribe
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    int updateByPrimaryKey(Subscribe record);
}