package com.sealll.bean;

public class Perm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.per_id
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    private String perId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.fav_per
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    private String favPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.sub_per
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    private String subPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.rep_per
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    private String repPer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.uid
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    private String uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.per_id
     *
     * @return the value of permission.per_id
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public String getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.per_id
     *
     * @param perId the value for permission.per_id
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public void setPerId(String perId) {
        this.perId = perId == null ? null : perId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.fav_per
     *
     * @return the value of permission.fav_per
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public String getFavPer() {
        return favPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.fav_per
     *
     * @param favPer the value for permission.fav_per
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public void setFavPer(String favPer) {
        this.favPer = favPer == null ? null : favPer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.sub_per
     *
     * @return the value of permission.sub_per
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public String getSubPer() {
        return subPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.sub_per
     *
     * @param subPer the value for permission.sub_per
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public void setSubPer(String subPer) {
        this.subPer = subPer == null ? null : subPer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.rep_per
     *
     * @return the value of permission.rep_per
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public String getRepPer() {
        return repPer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.rep_per
     *
     * @param repPer the value for permission.rep_per
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public void setRepPer(String repPer) {
        this.repPer = repPer == null ? null : repPer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.uid
     *
     * @return the value of permission.uid
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.uid
     *
     * @param uid the value for permission.uid
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }
}