package com.sealll.bean;

import java.util.ArrayList;
import java.util.List;

public class PermExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public PermExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPerIdIsNull() {
            addCriterion("per_id is null");
            return (Criteria) this;
        }

        public Criteria andPerIdIsNotNull() {
            addCriterion("per_id is not null");
            return (Criteria) this;
        }

        public Criteria andPerIdEqualTo(String value) {
            addCriterion("per_id =", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotEqualTo(String value) {
            addCriterion("per_id <>", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdGreaterThan(String value) {
            addCriterion("per_id >", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdGreaterThanOrEqualTo(String value) {
            addCriterion("per_id >=", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdLessThan(String value) {
            addCriterion("per_id <", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdLessThanOrEqualTo(String value) {
            addCriterion("per_id <=", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdLike(String value) {
            addCriterion("per_id like", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotLike(String value) {
            addCriterion("per_id not like", value, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdIn(List<String> values) {
            addCriterion("per_id in", values, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotIn(List<String> values) {
            addCriterion("per_id not in", values, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdBetween(String value1, String value2) {
            addCriterion("per_id between", value1, value2, "perId");
            return (Criteria) this;
        }

        public Criteria andPerIdNotBetween(String value1, String value2) {
            addCriterion("per_id not between", value1, value2, "perId");
            return (Criteria) this;
        }

        public Criteria andFavPerIsNull() {
            addCriterion("fav_per is null");
            return (Criteria) this;
        }

        public Criteria andFavPerIsNotNull() {
            addCriterion("fav_per is not null");
            return (Criteria) this;
        }

        public Criteria andFavPerEqualTo(String value) {
            addCriterion("fav_per =", value, "favPer");
            return (Criteria) this;
        }

        public Criteria andFavPerNotEqualTo(String value) {
            addCriterion("fav_per <>", value, "favPer");
            return (Criteria) this;
        }

        public Criteria andFavPerGreaterThan(String value) {
            addCriterion("fav_per >", value, "favPer");
            return (Criteria) this;
        }

        public Criteria andFavPerGreaterThanOrEqualTo(String value) {
            addCriterion("fav_per >=", value, "favPer");
            return (Criteria) this;
        }

        public Criteria andFavPerLessThan(String value) {
            addCriterion("fav_per <", value, "favPer");
            return (Criteria) this;
        }

        public Criteria andFavPerLessThanOrEqualTo(String value) {
            addCriterion("fav_per <=", value, "favPer");
            return (Criteria) this;
        }

        public Criteria andFavPerLike(String value) {
            addCriterion("fav_per like", value, "favPer");
            return (Criteria) this;
        }

        public Criteria andFavPerNotLike(String value) {
            addCriterion("fav_per not like", value, "favPer");
            return (Criteria) this;
        }

        public Criteria andFavPerIn(List<String> values) {
            addCriterion("fav_per in", values, "favPer");
            return (Criteria) this;
        }

        public Criteria andFavPerNotIn(List<String> values) {
            addCriterion("fav_per not in", values, "favPer");
            return (Criteria) this;
        }

        public Criteria andFavPerBetween(String value1, String value2) {
            addCriterion("fav_per between", value1, value2, "favPer");
            return (Criteria) this;
        }

        public Criteria andFavPerNotBetween(String value1, String value2) {
            addCriterion("fav_per not between", value1, value2, "favPer");
            return (Criteria) this;
        }

        public Criteria andSubPerIsNull() {
            addCriterion("sub_per is null");
            return (Criteria) this;
        }

        public Criteria andSubPerIsNotNull() {
            addCriterion("sub_per is not null");
            return (Criteria) this;
        }

        public Criteria andSubPerEqualTo(String value) {
            addCriterion("sub_per =", value, "subPer");
            return (Criteria) this;
        }

        public Criteria andSubPerNotEqualTo(String value) {
            addCriterion("sub_per <>", value, "subPer");
            return (Criteria) this;
        }

        public Criteria andSubPerGreaterThan(String value) {
            addCriterion("sub_per >", value, "subPer");
            return (Criteria) this;
        }

        public Criteria andSubPerGreaterThanOrEqualTo(String value) {
            addCriterion("sub_per >=", value, "subPer");
            return (Criteria) this;
        }

        public Criteria andSubPerLessThan(String value) {
            addCriterion("sub_per <", value, "subPer");
            return (Criteria) this;
        }

        public Criteria andSubPerLessThanOrEqualTo(String value) {
            addCriterion("sub_per <=", value, "subPer");
            return (Criteria) this;
        }

        public Criteria andSubPerLike(String value) {
            addCriterion("sub_per like", value, "subPer");
            return (Criteria) this;
        }

        public Criteria andSubPerNotLike(String value) {
            addCriterion("sub_per not like", value, "subPer");
            return (Criteria) this;
        }

        public Criteria andSubPerIn(List<String> values) {
            addCriterion("sub_per in", values, "subPer");
            return (Criteria) this;
        }

        public Criteria andSubPerNotIn(List<String> values) {
            addCriterion("sub_per not in", values, "subPer");
            return (Criteria) this;
        }

        public Criteria andSubPerBetween(String value1, String value2) {
            addCriterion("sub_per between", value1, value2, "subPer");
            return (Criteria) this;
        }

        public Criteria andSubPerNotBetween(String value1, String value2) {
            addCriterion("sub_per not between", value1, value2, "subPer");
            return (Criteria) this;
        }

        public Criteria andRepPerIsNull() {
            addCriterion("rep_per is null");
            return (Criteria) this;
        }

        public Criteria andRepPerIsNotNull() {
            addCriterion("rep_per is not null");
            return (Criteria) this;
        }

        public Criteria andRepPerEqualTo(String value) {
            addCriterion("rep_per =", value, "repPer");
            return (Criteria) this;
        }

        public Criteria andRepPerNotEqualTo(String value) {
            addCriterion("rep_per <>", value, "repPer");
            return (Criteria) this;
        }

        public Criteria andRepPerGreaterThan(String value) {
            addCriterion("rep_per >", value, "repPer");
            return (Criteria) this;
        }

        public Criteria andRepPerGreaterThanOrEqualTo(String value) {
            addCriterion("rep_per >=", value, "repPer");
            return (Criteria) this;
        }

        public Criteria andRepPerLessThan(String value) {
            addCriterion("rep_per <", value, "repPer");
            return (Criteria) this;
        }

        public Criteria andRepPerLessThanOrEqualTo(String value) {
            addCriterion("rep_per <=", value, "repPer");
            return (Criteria) this;
        }

        public Criteria andRepPerLike(String value) {
            addCriterion("rep_per like", value, "repPer");
            return (Criteria) this;
        }

        public Criteria andRepPerNotLike(String value) {
            addCriterion("rep_per not like", value, "repPer");
            return (Criteria) this;
        }

        public Criteria andRepPerIn(List<String> values) {
            addCriterion("rep_per in", values, "repPer");
            return (Criteria) this;
        }

        public Criteria andRepPerNotIn(List<String> values) {
            addCriterion("rep_per not in", values, "repPer");
            return (Criteria) this;
        }

        public Criteria andRepPerBetween(String value1, String value2) {
            addCriterion("rep_per between", value1, value2, "repPer");
            return (Criteria) this;
        }

        public Criteria andRepPerNotBetween(String value1, String value2) {
            addCriterion("rep_per not between", value1, value2, "repPer");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("uid like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("uid not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table permission
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 30 08:50:00 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table permission
     *
     * @mbg.generated Tue Mar 30 08:50:00 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}