package com.sealll.bean;

public class ReplyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.p_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reply.re_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    private String reId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.p_id
     *
     * @return the value of reply.p_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.p_id
     *
     * @param pId the value for reply.p_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setpId(String pId) {
        this.pId = pId == null ? null : pId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reply.re_id
     *
     * @return the value of reply.re_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public String getReId() {
        return reId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reply.re_id
     *
     * @param reId the value for reply.re_id
     *
     * @mbg.generated Sun Mar 28 15:51:14 CST 2021
     */
    public void setReId(String reId) {
        this.reId = reId == null ? null : reId.trim();
    }
}