package com.sealll.application.message.bean;

import java.io.Serializable;
import java.util.Date;

public class Message2 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.m_id
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    private String mId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.mtitle
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    private String mtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.time
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.uid
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    private String uid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.m_id
     *
     * @return the value of message.m_id
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    public String getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.m_id
     *
     * @param mId the value for message.m_id
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    public void setmId(String mId) {
        this.mId = mId == null ? null : mId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.mtitle
     *
     * @return the value of message.mtitle
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    public String getMtitle() {
        return mtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.mtitle
     *
     * @param mtitle the value for message.mtitle
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    public void setMtitle(String mtitle) {
        this.mtitle = mtitle == null ? null : mtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.time
     *
     * @return the value of message.time
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.time
     *
     * @param time the value for message.time
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.uid
     *
     * @return the value of message.uid
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.uid
     *
     * @param uid the value for message.uid
     *
     * @mbg.generated Sun May 16 18:44:38 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }
}