package com.sealll.application.tag.bean;

import com.sealll.application.post.bean.Post;

import java.util.ArrayList;
import java.util.List;

public class Tag {

    private String tag;
    private String tagname;
    private Integer posts;
    private List<Post> list;

    public List<Post> getList() {
        return list;
    }

    public void setList(List<Post> list) {
        this.list = list;
    }

    public Tag(String tag, String tagname) {
        this.tag = tag;
        this.tagname = tagname;
    }

    public Tag() {
    }


    public Integer getPosts() {
        return posts;
    }

    public void setPosts(Integer posts) {
        this.posts = posts;
    }

    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag
     *
     * @param tag the value for tag.tag
     *
     * @mbg.generated Fri May 07 15:27:39 CST 2021
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tagname
     *
     * @return the value of tag.tagname
     *
     * @mbg.generated Fri May 07 15:27:39 CST 2021
     */
    public String getTagname() {
        return tagname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tagname
     *
     * @param tagname the value for tag.tagname
     *
     * @mbg.generated Fri May 07 15:27:39 CST 2021
     */
    public void setTagname(String tagname) {
        this.tagname = tagname == null ? null : tagname.trim();
    }
}