package com.sealll.application.user.bean;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.uid
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.username
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.password
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.reg_time
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    private Date regTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.email
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.uid
     *
     * @return the value of User.uid
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.uid
     *
     * @param uid the value for User.uid
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.username
     *
     * @return the value of User.username
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.username
     *
     * @param username the value for User.username
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.password
     *
     * @return the value of User.password
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.password
     *
     * @param password the value for User.password
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.reg_time
     *
     * @return the value of User.reg_time
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    public Date getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.reg_time
     *
     * @param regTime the value for User.reg_time
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    public void setRegTime(Date regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.email
     *
     * @return the value of User.email
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.email
     *
     * @param email the value for User.email
     *
     * @mbg.generated Tue Apr 20 10:43:18 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}